### ISSUE TITLE
It is normal to set the PVP arena area, but it is invalid to set the safe area.

### ISSUE THREAD

**Issue by BuBing13** [Odjit/KindredArenas#1]
I'm on my server. When players enter the server, they always have a protective BUFF. This is a global protective BUFF. When I set up the pvp arena area, PVP is successfully turned on. People can fight in the arena area, but What I wanted was the opposite setup, I wanted to create protected areas where people couldn't fight, but that didn't work out. No matter how I changed it, there was always a global protected area.

**Comment by Odjit** [comment]
I know we addressed this on discord, but just to respond here so it doesn't appear ignored: 

Default behavior is indeed the buff protecting everyone from world pvp, and it coming off in arenas.
To use elysiums, you must set a pvptime to "turn on" world pvp, and only have it protect in safe zones.
